"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['My_Daily_Q.py']
DATA_FILES = ['assignments.pkl']
OPTIONS = {'iconfile': '/Users/ptumulty/Documents/VS_Code/MyDailyQ_WX/MDQLogo.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
